name: biome

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: HUSKY=0 npm ci

      - name: Biome CI
        run: npm run biome:ci

